import { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Site.module.css';

import Card from '../components/card';

type Task = {
    description: string;
    slug: string;
};

type Props = {
    id: string;
    title: string;
    tasks: Array<Task>;
};

export const getServerSideProps = async () => {
    const res = await fetch('https://5cadf493845049001423c167.mockapi.io/list');
    const data = await res.json();
    return { props: data[0] };
};

const Home = ({ title, tasks }: Props) => {
    const [isHydrating, setIsHydrating] = useState(true);

    useEffect(() => {
        setIsHydrating(false);
        //setTimeout(() => setIsHydrating(false), 1000);
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Next JS PoC</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/arale.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>{title}</h1>
                <div className={styles.tasks}>
                    {tasks.map((task, i) => (
                        <Card
                            title={`Task ${i}`}
                            key={`Task ${i}`}
                            description={task.description}
                            disabled={isHydrating}
                        />
                    ))}
                </div>
            </main>
        </div>
    );
};

export default Home;
